image: chybie/node-aws-cli
options:
    size: 2x
pipelines:
  branches:
    master:
      - step:
          script:
            - NODE_OPTIONS=--max_old_space_size=4096
            - yarn --ignore-engines install
            - git submodule update --init --recursive
            - CI=false yarn build
            - aws s3 --region "us-west-1" rm s3://dash.oelement.net
            - aws s3 --region "us-west-1" sync . s3://dash.oelement.net --exclude "node_modules/*"
            - aws cloudfront create-invalidation --distribution-id EYMRDI76QF7E0 --paths /*