import { createActionTypes } from 'utils'

export const REST_API = createActionTypes('REST_API', [
  'GET',
  'GET_ONE',
  'SAVE',
  'PUT',
  'PATCH',
  'DELETE',
  'SUCCESS',
  'FAILURE',
])
export const UI = createActionTypes('UI', ['TOGGLE_LEFT_SIDEBAR', 'UPDATE_LEFT_SIDEBAR_INFO'])
export const GRAPHQL_API = createActionTypes('GRAPHQL_API', [
  // Announcer
  'NOTIFICATIONS_GET_REQUEST',
  'NOTIFICATIONS_GET_SUCCESS',
  'NOTIFICATIONS_GET_FAILURE',
  'NOTIFICATIONS_SAVE_REQUEST',
  'NOTIFICATIONS_SAVE_SUCCESS',
  'NOTIFICATIONS_SAVE_FAILURE',
  'ACTIONBANNER_GET_REQUEST',
  'ACTIONBANNER_GET_SUCCESS',
  'ACTIONBANNER_GET_FAILURE',
  'ACTIONBANNER_SAVE_REQUEST',
  'ACTIONBANNER_SAVE_SUCCESS',
  'ACTIONBANNER_SAVE_FAILURE',
  'NEWS_GET_REQUEST',
  'NEWS_GET_SUCCESS',
  'NEWS_GET_FAILURE',
  'NEWS_SAVE_REQUEST',
  'NEWS_SAVE_SUCCESS',
  'NEWS_SAVE_FAILURE',
  'CHANGE_STATUS_MESSAGE',

  // Editor
  'IMAGES_GET_REQUEST',
  'IMAGES_GET_SUCCESS',
  'IMAGES_GET_FAILURE',
  'CONTENTS_PRESAVE_REQUEST',
  'CONTENTS_PRESAVE_SUCCESS',
  'CONTENTS_PRESAVE_FAILURE',
  'GALLERIES_GET_REQUEST',
  'GALLERIES_GET_SUCCESS',
  'GALLERIES_GET_FAILURE',
  'GALLERIES_ADDUPDATE_REQUEST',
  'GALLERIES_ADDUPDATE_SUCCESS',
  'GALLERIES_ADDUPDATE_FAILURE',
  'IMAGES_SAVE_REQUEST',
  'IMAGES_SAVE_SUCCESS',
  'IMAGES_SAVE_FAILURE',
  'GALLERIES_SAVE_REQUEST',
  'GALLERIES_SAVE_SUCCESS',
  'GALLERIES_SAVE_FAILURE',
  'CONTENTS_SAVE_REQUEST',
  'CONTENTS_SAVE_SUCCESS',
  'CONTENTS_SAVE_FAILURE',
  'COLLECTIONS_GET_REQUEST',
  'COLLECTIONS_GET_SUCCESS',
  'COLLECTIONS_GET_FAILURE',
  'COLLECTIONS_SAVE_REQUEST',
  'COLLECTIONS_SAVE_SUCCESS',
  'COLLECTIONS_SAVE_FAILURE',
  'DATA_GET_REQUEST',
  'DATA_GET_SUCCESS',
  'DATA_GET_FAILURE',
  'BYOE_GET_REQUEST',
  'BYOE_GET_SUCCESS',
  'BYOE_GET_FAILURE',
])

export const STATUS_MSG = createActionTypes('STATUS_MSG', ['SET_STATUS_MSG'])
export const SAVE_PAGE_INFO = 'SAVE_PAGE_INFO'
export const CHANGE_PAGE_LINK = 'CHANGE_PAGE_LINK'
export const RESET_STORE = 'RESET_STORE'
export const RECORDS = createActionTypes('STORIES', [
  'ADD_RECORD',
  'REMOVE_RECORD',
  'EDIT_RECORD',
  'SELECT_RECORD',
])
export default {
  REST_API,
  GRAPHQL_API,
  STATUS_MSG,
  SAVE_PAGE_INFO,
  CHANGE_PAGE_LINK,
  RESET_STORE,
  UI,
  RECORDS,
}
