// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_content_delivery_bucket: 'oelement-login-hostingbucket-master',
  aws_content_delivery_bucket_region: 'us-east-1',
  aws_content_delivery_url:
    'http://oelement-login-hostingbucket-master.s3-website-us-east-1.amazonaws.com',
  aws_cognito_identity_pool_id:
    'us-east-1:4327e15b-e10f-46c2-8f56-d59afbb02357',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_cwodze0i9',
  aws_user_pools_web_client_id: '7ieff3834r5usrvoug8pu2g5tn',
}

export default awsmobile
